#!/bin/bash
set -e
mkdir -p $1

cat > $1/1.py << EOF

import sys

for line in sys.stdin.readlines():
  
EOF

cat > $1/1.lua << EOF

for line in io.lines() do

end

EOF

~/go/bin/aocdl -wait -output $1/i -day $1
